// src/components/NavBar.jsx
import { usePets } from '../context/PetsContext'

export default function NavBar() {
  const { matchCount, navigate, view } = usePets()

  return (
    <nav className="fixed bottom-0 inset-x-0 z-50 nav-glass">
      <div className="max-w-lg mx-auto flex items-center justify-around h-16">
        <button
          onClick={() => navigate('home')}
          className={`nav-item ${view === 'home' ? 'nav-item--active' : ''}`}
        >
          <svg className="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
            <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
            <polyline points="9 22 9 12 15 12 15 22" />
          </svg>
          <span className="nav-label">Inicio</span>
        </button>

        <button
          onClick={() => navigate('filtros')}
          className={`nav-item ${view === 'filtros' ? 'nav-item--active' : ''}`}
        >
          <svg className="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
            <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
          </svg>
          <span className="nav-label">Filtros</span>
        </button>

        <button
          onClick={() => navigate('matches')}
          className={`nav-item ${view === 'matches' ? 'nav-item--active' : ''}`}
        >
          <div className="relative">
            <svg className="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
              <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z" />
            </svg>
            {matchCount > 0 && (
              <span className="absolute -top-1.5 -right-2.5 bg-rose-500 text-white text-[10px] font-bold rounded-full min-w-[18px] h-[18px] flex items-center justify-center px-1">
                {matchCount}
              </span>
            )}
          </div>
          <span className="nav-label">Matches</span>
        </button>
      </div>
    </nav>
  )
}

// src/components/NavBar.vue
<script setup>
import { usePetsStore } from '../stores/pets'

const store = usePetsStore()
</script>

<template>
  <nav class="fixed bottom-0 inset-x-0 z-50 nav-glass">
    <div class="max-w-lg mx-auto flex items-center justify-around h-16">
      <!-- Home / Swipe -->
      <router-link
        :to="{ name: 'home' }"
        class="nav-item"
        active-class="nav-item--active"
      >
        <svg class="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
          <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
          <polyline points="9 22 9 12 15 12 15 22" />
        </svg>
        <span class="nav-label">Inicio</span>
      </router-link>

      <!-- Filtros -->
      <router-link
        :to="{ name: 'filtros' }"
        class="nav-item"
        active-class="nav-item--active"
      >
        <svg class="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
          <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
        </svg>
        <span class="nav-label">Filtros</span>
      </router-link>

      <!-- Matches -->
      <router-link
        :to="{ name: 'matches' }"
        class="nav-item"
        active-class="nav-item--active"
      >
        <div class="relative">
          <svg class="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
            <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z" />
          </svg>
          <span
            v-if="store.matchCount > 0"
            class="absolute -top-1.5 -right-2.5 bg-rose-500 text-white text-[10px] font-bold rounded-full min-w-[18px] h-[18px] flex items-center justify-center px-1"
          >
            {{ store.matchCount }}
          </span>
        </div>
        <span class="nav-label">Matches</span>
      </router-link>
    </div>
  </nav>
</template>

<style scoped>
.nav-glass {
  backdrop-filter: blur(20px) saturate(1.5);
  -webkit-backdrop-filter: blur(20px) saturate(1.5);
  background: rgb(10 10 20 / 0.75);
  border-top: 1px solid rgb(255 255 255 / 0.06);
}

.nav-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2px;
  color: rgb(255 255 255 / 0.35);
  transition: color 0.25s ease;
  text-decoration: none;
  padding: 0.5rem 1rem;
}

.nav-item:hover {
  color: rgb(255 255 255 / 0.6);
}

.nav-item--active {
  color: white;
}

.nav-label {
  font-size: 0.65rem;
  font-weight: 500;
  letter-spacing: 0.02em;
}
</style>
